PROJECT: "bop"
DTA_FOLDER: "dta"
DTA_OUTPUT_FOLDER: "dta/output"
DTA_OUTPUT_RDS_FOLDER: "dta/output/RDS"
MDL_FOLDER: "dta/models"
RAW_DTA_FOLDER: "dta/raw-dta"
IMG_FOLDER: "img"
TXT_FOLDER: "txt"
SRC_FOLDER: "src"

NSECCIONS: 160
NMOSTRES: 1
NMILLORMOSTRES: 3
PERIODE: 2017

ABSCORRECCIO: 8

MEAN_ENQUESTES_SEC: 12.5
MIN_ENQUESTES_SEC: 11
MAX_ENQUESTES_SEC: 13

MEAN_ENQUESTES_SEC_COR: 9.5
MIN_ENQUESTES_SEC_COR: 8
MAX_ENQUESTES_SEC_COR: 11

LATCEO: 41.39383224082219
LONGCEO: 2.166174748226288

LEVEL: 0.95

MAXIM_MUNICIPIS: 95
